Fixes
sugarlabs/CowBulls-activity pull request #17
Opened 2020-06-10 03:45 UTC by JuiP

WIP

- [x] Port to python3

- [ ] Clicking on the level drop down, no other levels are shown when hard level is selected

- [ ] Two mouse corsors seen when moving the mouse over to the toolbar

- [ ] Clicking on the area beside 3,6,9 number buttons : mouse clicks enters number 4 and 7 in the dash

- [ ] Clicking on the toolbar and then the add to desciption button causes black screen

- [ ] Hard level dashes do not fit the screen

2020-06-10 15:18 UTC, srevinsaju requested changes
Looks good. Did a code review; will test this soon :smile:
very descriptive commit messages :+1:

2020-06-10 15:18 UTC, srevinsaju commented on CowBulls.py
> +            self.clock.tick(20) # Try to stay at 20 FPS
flake: E261 at least two spaces before inline comment

2020-06-10 15:18 UTC, srevinsaju commented on activity.py
> +
flake: Trailing space

2020-06-10 15:18 UTC, srevinsaju commented on g.py
> +    scale = min([w / 1200.0, h / 900.0])
My suggestion, it would be great if `tuple` is used instead of `list`; not necessayy however

2020-06-10 15:18 UTC, srevinsaju commented on icons/new-game.svg
> +   style="fill:#ffffff;fill-opacity:1;stroke:#282828;stroke-width:1.72267997;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none" /></svg>
Missing newline at end of file

2020-06-10 15:18 UTC, srevinsaju commented on utils.py
> +                num = random.sample(list(range(0, 10)), 3)
```python
>>> random.sample(range(0,10), 3)
[5, 0, 7]
>>> random.sample(range(0,10), 3)
[3, 9, 6]
>>> random.sample(range(0,10), 3)
[5, 6, 9]
>>> 
```
As you can see, there is no need of the `list` function, As mentioned [here](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md),
> Port from Python 2 to Python 3. Start your porting with 2to3 tool,
> In the terminal, type:
> `2to3 -w -n *.py`
> and then **_review_ every change made,**

2020-06-10 15:18 UTC, srevinsaju commented on utils.py
> +            num = [random.choice(list(range(0, 10))) for x in range(level)]
This could be better written as
```python
num = [random.randint(0, 10) for _ in range(level)]
```
Additionally, I have also replaced `x` with `_`, so that we can avoid `F401` as part of `flake8`

2020-06-11 12:20 UTC, JuiP commented on CowBulls.py
> +            self.clock.tick(20) # Try to stay at 20 FPS
Done in b616cef

2020-06-11 12:21 UTC, JuiP commented on activity.py
> +
Done in b616cef

2020-06-11 12:32 UTC, JuiP commented on utils.py
> +            num = [random.choice(list(range(0, 10))) for x in range(level)]
Done in 96e5e4b

2020-06-11 12:32 UTC, JuiP commented on utils.py
> +                num = random.sample(list(range(0, 10)), 3)
Thanks for noticing! Done in 96e5e4b

2020-06-11 12:32 UTC, JuiP commented on icons/new-game.svg
> +   style="fill:#ffffff;fill-opacity:1;stroke:#282828;stroke-width:1.72267997;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none" /></svg>
Done in 96e5e4b

2020-06-11 12:33 UTC, JuiP commented on g.py
> +    scale = min([w / 1200.0, h / 900.0])
I don't think this is a necessary change, why do you think `tuple` should be used?

2020-06-11 13:58 UTC, JuiP commented
- [ ] Two mouse corsors seen when moving the mouse over to the toolbar. 

- [ ] smile is not centered

These two are related. I'm guessing, the pygame canvas is shifted and I don't know why. The smile should have been centered because [this](https://github.com/sugarlabs/CowBulls-activity/blob/9ef2fde2fb16f9180f067326f2abccd43bcf6be2/CowBulls.py#L83) line of code passes width/2 as the position.

The cursor here is stuck and as soon as you move the cursor to the toolbar, there are two cursors. I didn't notice before but this can be reproduced in many activities.
![cursor](https://user-images.githubusercontent.com/46154968/84393374-1f72d280-ac19-11ea-9836-307dcf929cda.png)

2020-07-03 05:34 UTC, JuiP commented
Tested; worked like expected.
@srevinsaju @chimosky @quozl Please test, review and merge :)

2020-07-06 13:31 UTC, chimosky commented
Reviewed, tested. Thanks.

The mouse issue you noticed still persists, have you found the cause or any speculations?
I'm yet to take a look.

2020-07-06 13:52 UTC, JuiP commented
Thanks! :)

Regarding the mouse issue, seems like it happens in every game that uses pygame, @quozl confirmed in [comment](https://github.com/sugarlabs/jumble-activity/pull/10#discussion_r447476763)

2020-07-06 14:36 UTC, chimosky commented
Thanks for that.

2020-07-06 14:36 UTC, merged